### ISSUE TITLE
Words with accent marks

### ISSUE THREAD

**Issue by jmhostalet** [apidoc/grunt-apidoc#14]
Words with accent marks are not displayed properly, for example

áéíóú in name parameter at apidoc.json, is not displayed properly at web

Thank you

**Comment by rottmann** [comment]
Can't reproduce this. Can you mail me the generated doc dir?

**Comment by jmhostalet** [comment]
I've solved this problem saving apidoc.json as UTF-8 instead of ANSI
(Windows default encoding)

In ANSI this json

{
  "name": "api",
  "version": "1.0.0",
  "description": "a social events application - aáeéiíoóuú",
  "title": "api doc",
  "url" : "http://127.0.0.1"
}

generates this output

[image: Inline image 1]

maybe a warning about ANSI encoding during docu generation would be helpful.

Thank you for your work, it is a great tool, and it is very very helpful
for my team.

**Comment by rottmann** [comment]
Ok, had already thought it would be a encoding problem.
Will add an encoding warning in the next version.
