### ISSUE TITLE
parse error when using non-english charset in @api title

### ISSUE THREAD

**Issue by hitdavid** [apidoc/grunt-apidoc#15]
parse error when using non-english charset in @api title

when I use chinese chars in @api title (eg. @api {get} /foo/bar 中文)
the api_data.js file generated is incomplete.
the value of title field after name will appears like "name" : "_______"

some of api will not show in web html page

**Comment by hitdavid** [comment]
a patch to make apidoc right

#python script

author = 'David'
import os

file_object = open('./apidoc/api_data.js')
dest = open('./apidoc/api_data.js.new', 'w')

name = ''
title_line_number = 0
name_line_number = 0
line_number = 0

result = ''

for line in file_object:
line_number += 1
if line.contains("\"title\""):
strList = line.split(':')
name = strList[1]
title_line_number = line_number
result = line
else:
if line.contains("\"name\""):
if line_number == title_line_number + 1:
valueList = line.split(':')
result = valueList[0] + ':' + strList[1]
else:
result = line
else:
result = line
dest.write(result)

file_object.close()
dest.close()

os.remove('./apidoc/api_data.js')
open('./apidoc/api_data.js', "wb").write(open('./apidoc/api_data.js.new', "rb").read())

**Comment by prakashmuvi** [comment]
Hi,
Apidocjs  is working fine in my windows system .I am getting parse error in linux system. I am not finding the root cause of this problem. is there any dependency of server or version ? I have used command line script apidoc -i  absolute_source-path -o absolute-target-path.
