### ISSUE TITLE
Warning: parse plugin... , while apidoc parse .php file with phpDocumentor comments

### ISSUE THREAD

**Issue by wadziu** [apidoc/grunt-apidoc#16]
**Calling:**  apidoc -i Controller/Product/Selection/ -o ~/public_html/Api_doc/ --v |more

**Results:**
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.12.1
verbose: apidoc-core version: 0.3.1
verbose: apidoc-spec version: 0.2.0
verbose: run parser
warn: parser plugin 'var' not found in block: 3
verbose: parse file: Controller/Product/Selection/View.class.php

I have check that file , my apidoc comments is correct but when in block 3 I remove comment 
`/** @var \Model\Product\Selection\Group\Collection $groups */`

everything works fine. 

The problem is I do have more this kind of comments in this file and it does not make any problems, just this one :/

Can I just somehow force apidoc to ignore phpDoc comments ?

**Comment by rottmann** [comment]
Can you check if a previously opened block is not closed ?

Or can you send me the file rottmann@inveris.de

**Comment by wadziu** [comment]
I did checked, all looks fine :/
I've sent you file within an email. Thanks in advance.

**Comment by rottmann** [comment]
Thanks, found the problem. Will fix it in the next release (hope within the next week).

Currently the close comment `*/` must be in a new line.

Quickfix to enable single lines:

In file:
`apidoc/node_modules/apidoc-core/lib/languages/default.js`

Replace line:
`    docBlocksRegExp: /\/\*\*\uffff?(.+?)\uffff(?:\s*)?\*\//g,`

with:
`    docBlocksRegExp: /\/\*\*\uffff?(.+?)\uffff?(?:\s*)?\*\//g,`
(only a missing ?)

**Comment by wadziu** [comment]
Thank you very much for help.
