### ISSUE TITLE
@apiSuccess field does not accept special characters

### ISSUE THREAD

**Issue by Noxen** [apidoc/grunt-apidoc#17]
Hello,

I just ran into an issue with the parser.
Turns out that for apiSuccess, the field does not allow me to put a semicolon in it, but get parsed and what's after the semicolon get sent to the description.
``` php
/**
* ...
* @apiSuccess (200) {String} og:test Meta tags test.
*/
```

The result is gonna be like this :

Field | Type | Description
------------ | ------------- | -------------
og | String | :test Meta tags test.

Therefore I was wondering if you guys ever ran into this and if you had a solution for that.
I tried to encode, but nothing worked so far...

Thanks for your time :)

**Comment by rottmann** [comment]
Added support for `:` in Names in the next release.
