### ISSUE TITLE
apiParam generating type as extra HTML element in Documentation page

### ISSUE THREAD

**Issue by sincerekamal** [apidoc/grunt-apidoc#19]
Hi Team,

Today I encountered a minor weird issue, I added 

```` @apiParam {string{4..63}} id Value for ID field ````

to my API documentation. In the generated, there is an extra ```` <p> ```` tag in right side of input as in the below image.

![image](https://cloud.githubusercontent.com/assets/3885228/8160982/46be8486-1391-11e5-8809-ad979856c988.png)

**Comment by rottmann** [comment]
Thanks. Bug is known and will be fixed on the next release (hope on Friday).
