### ISSUE TITLE
Api docs versioning and history.

### ISSUE THREAD

**Issue by kkilaru** [apidoc/grunt-apidoc#21]
Is there a way to create and maintain history/versioning without manually having to create a copy of the old block (to a history file - _apidoc.js)? Something along the lines of providing the location of the old docs at apidoc generation time, which would then check for differences between the old docs and the new ones to generate history/versioning? 

Needing to create copies of the old docs when they are modified seems to be a bit cumbersome.

**Comment by rottmann** [comment]
If somebody create a separate tool that compare / merge generated data files, this would be possible.

apidoc itself will not integrate this.

**Comment by kkilaru** [comment]
Thanks. Appreciate the response.

**Comment by VMBindraban** [comment]
+1 for this tool.
