### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by medaamarnadh** [apidoc/grunt-apidoc#23]
Hi guys ,

I am getting above error when i run apidoc grunt task .
Please help me to solve the issue.

And my grunt code is like this .

grunt.initConfig({
    apidoc:{
    	myapp:{
    		src:'routes/auth.js',
    		dest:'apidoc/'
    	}
    }
  });
  grunt.loadNpmTasks('grunt-apidoc');

  grunt.registerTask('apidoc',['apidoc']);

**Comment by rottmann** [comment]
try path only: `src: 'routes/' `

**Comment by medaamarnadh** [comment]
Hi thank you for quick response.

I tried this again it was getting same error.

**Comment by rottmann** [comment]
When you install and run apidoc (standalone with the parameters) what happen then?

**Comment by medaamarnadh** [comment]
Please take look at the attached screen shot

**Comment by rottmann** [comment]
Still have problem in a newer Version?
