### ISSUE TITLE
Restful API URLs

### ISSUE THREAD

**Issue by masg** [apidoc/grunt-apidoc#24]
Any help on how to set the restful API URLs? When I browse http://mydomain.com/apidoc/user, I am getting that the requested URL was not found on this server. 

I followed this guide http://apidocjs.com/ and I can access the index.html which shows my methods. Any suggestions please?

**Comment by rottmann** [comment]
Use a hash and the id (groupname): `http://mydomain.com/apidoc/#api-user`
