### ISSUE TITLE
Can't specify example URL or get rid of it

### ISSUE THREAD

**Issue by rickwaugh1** [apidoc/grunt-apidoc#25]
I have specified the options in my grunt file, but I keep getting the local URL of my apidocs application in my documents. I believe I should see http://endpoint/com in my examples, or nothing at all, if I do the following:

	   apidoc:
	   {
		  myapp:
		  {
			src: "../api/controllers/",
			dest: "../docs/apidocs/",
			options: {
				url:"http://endpoint.com",
				sampleUrl:false
			}
		  }
		}

**Comment by rottmann** [comment]
https://github.com/apidoc/grunt-apidoc/issues/18#issuecomment-125493552

It is a part of `packageInfo` which currently always overwritten by file info (it is bug)

**Comment by rickwaugh1** [comment]
Ah. Thanks. I figured it was something like that.
