### ISSUE TITLE
FEATURE REQUEST: Make links to another API in text

### ISSUE THREAD

**Issue by amurchick** [apidoc/grunt-apidoc#26]
For example, I want in @apiDescription link to another API, e.g.
```
/**
* @apiDescription Logout from system (must be auth done via #api-Auth-login#)
*/
```
where `#api-Auth-login` - hash from url `/path-to-docs/index.html#api-Auth-login`

**Comment by rottmann** [comment]
Same as https://github.com/apidoc/apidoc/issues/178
