### ISSUE TITLE
info: Nothing to do

### ISSUE THREAD

**Issue by calloncampbell** [apidoc/grunt-apidoc#30]
Trying to generate doc for ASP.NET Web Api using C#. After installing ApiDoc, creating a apidoc.json file in the project root and running the following command...I get "info: Nothing to do". Where is the docs on info/error messages? What am I doing wrong?

`apidoc -I controllers/ --debug`

**Comment by rottmann** [comment]
https://github.com/apidoc/apidoc/issues/410
