### ISSUE TITLE
how to add file type like '.ashx'

### ISSUE THREAD

**Issue by SKYDA** [apidoc/grunt-apidoc#33]
how to add file type like '.ashx'

**Comment by rottmann** [comment]
View https://github.com/apidoc/apidoc-core/tree/master/lib/languages
for examples and
https://github.com/apidoc/apidoc-core/blob/master/lib/index.js#L48
where it is included.

You can write a plugin which extends apidoc with it: 
https://github.com/apidoc/apidoc-plugin-test
