### ISSUE TITLE
Feature Request: Add global 'apiDefine' file

### ISSUE THREAD

**Issue by tedwardsknowlysis** [apidoc/grunt-apidoc#36]
Is there a way to add a global definitions file? If not, can you add that as a feature? I'd like to be able to define reusable 'apiDefine' or other elements that I can use in multiple files.

Is that possible or can it be added?

Another way to approach this might be to add an additional @apiGlobalDef tag or something along those lines.

**Comment by rottmann** [comment]
All definitions are global, no matter in which file they are.

view Example: http://apidocjs.com/#example-full
_apidoc.js contains some globals which are used in example.js

**Comment by tedwardsknowlysis** [comment]
My bad. The documentation wasn't really clear on this and when I tried it (which I now realize my shared file wasn't included in the process), it didn't seem to work.
