### ISSUE TITLE
{"message":"Please create an apidoc.json configuration file.","level":"warn"} 

### ISSUE THREAD

**Issue by Miskoo995** [apidoc/grunt-apidoc#56]
Hey guys! 

I am new at this staff, wanted to install ApiDoc on Windows 10 and I run into some errors in my CMD. 
{"message":"Please create an apidoc.json configuration file.","level":"warn"} 

This one happens when I finish the installation. I guess it is some simple staff, but I am new at this. Any help is appreciated! :)

**Comment by rottmann** [comment]
http://apidocjs.com/#configuration

**Comment by olavomello** [comment]
Same problem here. I've the apidoc.json file in the api folder and get the error :

{"message":"apidoc.json\\package.json not found!","level":"debug"}
{"message":"Can not read: apidoc.json, please check the format (e.g. missing comma).","level":"error"}

**Comment by dorenta** [comment]
I too have the same issue 

`[public] node_modules/.bin/apidoc -c app/Containers/Documentation/ApiDocJs/public -f public.php  -i app -o public/api/documentation
Output: {"message":"Please create an apidoc.json configuration file.","level":"warn"}

[private] node_modules/.bin/apidoc -c app/Containers/Documentation/ApiDocJs/private -f private.php -f public.php  -i app -o public/api/private/documentation
Output: {"message":"Please create an apidoc.json configuration file.","level":"warn"}`
